export enum EntityNames {
  CLIENTE = 'cliente',
  ENDERECO = 'endereco',
  PROPRIEDADE = 'propriedade',
  ITEM = 'item',
  ITEM_BRANDING = 'item_branding',
  ITEM_GRUPO = 'item_grupo',
  PEDIDO = 'pedido',
  PEDIDO_ITEM = 'pedido_item',
  FATURAMENTO = 'faturamento',
  FATURAMENTO_ITEM = 'faturamento_item',
  PONTOS_PEDIDO = 'pontos_pedido',
  FUNCIONARIO = 'funcionario',
  CONDICAO_PAGAMENTO = 'condicao_pagamento',
  ESPECIE_PAGAMENTO = 'especie_pagamento',
  FORNECEDOR = 'fornecedor',
  CONTAS_PAGAR = 'contas_pagar',
  CONTAS_RECEBER = 'contas_receber',
  VENDEDOR = 'vendedor',
  ESTOQUE = 'estoque'
}
